language: node_js
node_js:
  - "10"
before_install: 'npm install -g jasmine-node'
install: 'npm i'
cache:
  directories:
    - node_modules
addons:
  sonarcloud:
    organization: "hugo-ter-doest-github"
script:
  - npm run test
  - npm run cover
  - sonar-scanner
